services:
  web:
    image: odoo:18.0
    restart: always
    user: "101:101"
    depends_on:
      - db
    ports:
      - "127.0.0.1:8069:8069"
      - "127.0.0.1:8072:8072"
    volumes:
      - .:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
      - /opt/odoo-data/filestore:/var/lib/odoo
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"

  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - /opt/odoo-data/postgres:/var/lib/postgresql/data
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "3"
